### ISSUE TITLE
Retour The movie quizz

### ISSUE THREAD

**Issue by LionelZoc** [cliffordten/de-movie-test#2]
- Le readme n’aide pas à bien configurer les variables d’environement (je n’y vois pas qu’il faut ajouter REDIS_HOST ou le SECRET par exemple ni comment configurer pour que le projet fonctionne avec le redis du docker 🛑 
- c'est top d'avoir utilisé des id uid ✅ 
- Lorsque je lance un register depuis appolo studio j'ai une erreur malgré le fait que l'utilisateur est crée. ✅ 🛑 
quand je teste sur la page web aussi ça marche mais j'ai cette erreur qui vient avec la data

```
mutation Register($input: UserInput!) {
  register(input: $input) {
    error {
      field
      message
    }
    user {
      id
      username
      email
      accessToken
      highestScore
      createdAt
      updatedAt
      quizResult {
        id
        noCorrectAnswers
        totalAnsweredQuestions
        currentScore
        userId
        createdAt
        updatedAt
        user {
          id
          username
          email
          accessToken
          highestScore
          createdAt
          updatedAt
        }
      }
    }
  }
}
```

<img width="1439" alt="Capture d’écran 2022-08-12 à 18 59 03" src="https://user-images.githubusercontent.com/8299128/184407810-f0842474-236b-45d9-9bf7-eb430655a804.png">

- bien que le login marche ça renvoi quand même une erreur dans la data retournée 🟡 
- cool d'avoir effectué des control dans les login et register resolver, top le logout resolver ✅ 
-  les spec du jeu ne sont pas respecté: le jeu ne s'arrete pas quand j'ai mal répondu à un quiz 🛑 🛑 
je vois que tu as implémenté une logique où tu récupère toutes les réponses de l'utilisateur dans le front avant de tout valider dans le back à la fin du timer mais bon c'est pas conforme à la demande
- sympa l'usage avancé de redis pour sauvegarder des données du jeux 👍🏾 
- sympa l'ajout de l'historique de jeux ✅ 
- usage du cache graphql ✅ 
- bon decoupage des composant dans le front ✅ 

# le jeux ne respecte pas les specifications 🛑 

ce serait top de pouvoir corriger les points remontés

**Comment by cliffordten** [comment]
ahhh okay. Je n'ai pas remarqué dans l'exigence que le jeu devait s'arrêter à la première mauvaise réponse du quiz. Bon, je travaille sur tout les point dans le issue.

**Comment by cliffordten** [comment]
addressed all issues
