### ISSUE TITLE
feedbacks

### ISSUE THREAD

**Issue by Valentino-Houessou** [cliffordten/de-movie-test#3]
- Pourquoi axios et pas fetch ?
- Pourquoi bcrypt et pas argon ?
- `imageBaseUrl` comme les autres url et les api keys auraient été préférable dans une constante et dans le fichier des variables d'environment

- super d'avoir rajouter un test dans le back
- super structure de projet
- Intéressant, l'usage de yup dans le back

**Comment by cliffordten** [comment]
Permettez-moi de répondre en anglais!

- Its a personal preference to use axios than fetch. Though there exist node-fetch, fetch api does not exist on node and i think it's experimental in node v17.

- I haven't heard about argon before. I have always used bcrypt for all my projects.

- It's a good idea to add `imageBaseUrl` to the config. I have updated it.

Thanks for the quiz.
